[2025-08-30 00:54:26.489639] https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_1_Base/filter.txt failed: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_1_Base/filter.txt
[2025-08-30 00:54:26.554261] https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Spyware/filter.txt failed: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Spyware/filter.txt
[2025-08-30 00:54:26.618745] https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Social/filter.txt failed: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Social/filter.txt
[2025-08-30 00:54:26.680166] https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_4_Annoyances/filter.txt failed: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_4_Annoyances/filter.txt
[2025-08-30 00:54:27.164487] https://curben.gitlab.io/malware-filter/urlhaus-filter-domains.txt failed: 403 Client Error: Forbidden for url: https://gitlab.com/users/sign_in
[2025-08-30 00:54:57.300069] https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt failed: HTTPSConnectionPool(host='osint.digitalside.it', port=443): Max retries exceeded with url: /Threat-Intel/lists/latestdomains.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd03cb71f90>, 'Connection to osint.digitalside.it timed out. (connect timeout=30)'))
[2025-08-30 00:55:23.860278] https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_1_Base/filter.txt failed: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_1_Base/filter.txt
[2025-08-30 00:55:23.893056] https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Spyware/filter.txt failed: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Spyware/filter.txt
[2025-08-30 00:55:24.201571] https://curben.gitlab.io/malware-filter/urlhaus-filter-domains.txt failed: 403 Client Error: Forbidden for url: https://gitlab.com/users/sign_in
[2025-08-30 00:55:54.339589] https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt failed: HTTPSConnectionPool(host='osint.digitalside.it', port=443): Max retries exceeded with url: /Threat-Intel/lists/latestdomains.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd03cb716d0>, 'Connection to osint.digitalside.it timed out. (connect timeout=30)'))
